### ISSUE TITLE
Suddenly Getting Error after not modifying settings.

### ISSUE THREAD

**Issue by TnnsBeast** [tanjeffreyz/planit#4]
Had this working for about a week, but now Im getting the following: 

 ! [remote rejected] main -> main (refusing to allow a GitHub App to create or update workflow `.github/workflows/main.yml` without `workflows` permission)
error: failed to push some refs to 'https://github.com/TnnsBeast/calendar'
Error: Process completed with exit code 1.

**Comment by tanjeffreyz** [comment]
Hi, can you check that this permission is still enabled?

![image](https://github.com/tanjeffreyz/planit/assets/69165598/2b352015-a570-43f0-80d0-ade758fa11b2)

If not, please try creating a new repository following the readme again. I ran into this issue some time ago too, suspecting it's due to GitHub updating its workflow token permissions
